version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8100:8000"
    environment:
      - ENV=sandbox
    volumes:
      - ./data/demo-data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3100:80"
    environment:
      - API_URL=http://localhost:8000

  db:
    image: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: scrap_demo
    volumes:
      - demo_db:/var/lib/postgresql/data

volumes:
  demo_db:
