# i18n.py
from __future__ import annotations
from typing import Dict

SUPPORTED_LANGS = ("en", "es", "zh")
DEFAULT_LANG = "en"

# Minimal keys you can expand anytime. Keep keys flat and stable.
_STRINGS: Dict[str, Dict[str, str]] = {
    "en": {
        "ok": "OK",
        "error": "Error",
        "login": "Login",
        "logout": "Logout",
        "buyer": "Buyer",
        "seller": "Seller",
        "admin": "Admin",
        "price_per_ton": "Price per ton",
        "total_value": "Total Value",
        "pickup_time": "Pickup Time",
        "delivery_time": "Delivery Time",
        "generated_by": "Generated by BRidge on",
        "bol": "Bill of Lading",
        "health_ok": "ok",
        "health_degraded": "degraded",
        "timezone": "Timezone",
        "language": "Language",
        "saved": "Saved",
    },
    "es": {
        "ok": "OK",
        "error": "Error",
        "login": "Iniciar sesión",
        "logout": "Cerrar sesión",
        "buyer": "Comprador",
        "seller": "Vendedor",
        "admin": "Administrador",
        "price_per_ton": "Precio por tonelada",
        "total_value": "Valor total",
        "pickup_time": "Hora de recogida",
        "delivery_time": "Hora de entrega",
        "generated_by": "Generado por BRidge el",
        "bol": "Carta de Porte",
        "health_ok": "ok",
        "health_degraded": "degradado",
        "timezone": "Zona horaria",
        "language": "Idioma",
        "saved": "Guardado",
    },
    "zh": {
        "ok": "确定",
        "error": "错误",
        "login": "登录",
        "logout": "退出",
        "buyer": "买方",
        "seller": "卖方",
        "admin": "管理员",
        "price_per_ton": "每吨价格",
        "total_value": "总金额",
        "pickup_time": "提货时间",
        "delivery_time": "交付时间",
        "generated_by": "由 BRidge 生成于",
        "bol": "提单",
        "health_ok": "正常",
        "health_degraded": "降级",
        "timezone": "时区",
        "language": "语言",
        "saved": "已保存",
    },
}

def t(key: str, lang: str | None) -> str:
    """Translate key for lang with English fallback."""
    lg = (lang or DEFAULT_LANG).lower()
    if lg not in _STRINGS:
        lg = DEFAULT_LANG
    return _STRINGS.get(lg, {}).get(key, _STRINGS[DEFAULT_LANG].get(key, key))

def strings_for(lang: str | None) -> Dict[str, str]:
    lg = (lang or DEFAULT_LANG).lower()
    if lg not in _STRINGS:
        lg = DEFAULT_LANG
    # Shallow copy so callers don't mutate canonical dict
    base = dict(_STRINGS[DEFAULT_LANG])
    base.update(_STRINGS[lg])
    return base
