# jobs.yaml
jobs:
  # ---------- ONE-TIME / ON-DEPLOY ----------
  - name: apply_migrations
    tag: deploy
    cmd: python /app/apply_migrations.py

  - name: seed_reference_data
    tag: deploy
    cmd: python /app/bridge_seed_reference_data.py

  # ---------- HOURLY (fast stuff / monitoring) ----------
  - name: indices_snapshot_builder
    tag: hourly
    cmd: python /app/indices_builder.py

  - name: carrier_monitor
    tag: hourly
    cmd: python /app/jobs/carrier_monitor.py

  # ---------- NIGHTLY (full battery) ----------
  # 1) DB & reference data safety (repeat nightly in case of drift)
  - name: nightly_apply_migrations
    tag: nightly
    cmd: python /app/apply_migrations.py

  - name: nightly_seed_reference_data
    tag: nightly
    cmd: python /app/bridge_seed_reference_data.py

  - name: import_vendor_material_map
    tag: nightly
    cmd: python /app/bridge_vendor_map_import.py

  # 2) Vendor ingests (run “all”, queue, specific sheets)
  - name: vendor_ingest_all
    tag: nightly
    cmd: python /app/bridge_vendor_ingest_all.py

  - name: vendor_ingest_queue
    tag: nightly
    cmd: python /app/run_vendor_ingest_queue.py

  - name: bridge_vendor_ingest
    tag: nightly
    cmd: python /app/bridge_vendor_ingest.py

  - name: ingest_cy_quote_sheet
    tag: nightly
    cmd: python /app/ingest_cy_quote_sheet.py

  - name: ingest_lewis_quotes
    tag: nightly
    cmd: python /app/ingest_lewis_quotes.py

  - name: ingest_vendor_quotes_csv
    tag: nightly
    cmd: python /app/ingest_vendor_quotes_csv.py

  # 3) Indices / forecasts
  # (De-duped): removed nightly indices_builder since hourly covers it.
  - name: forecast_job
    tag: nightly
    cmd: python /app/forecast_job.py

  # Publish “official” settles from history → indices_settlements
  - name: indices_publish_settles
    tag: nightly
    cmd: |
      python - <<'PY'
      import asyncio, datetime as dt
      from bridge_buyer_backend import indices_settle_publish, utcnow
      async def main():
          # publish using rule_version v1 for region=blended
          await indices_settle_publish(as_of=utcnow().date(), region="blended", rule_version="v1")
      asyncio.run(main())
      PY

  # Nightly backup snapshot (ZIP to Supabase/S3) with proof row
  - name: nightly_backup_snapshot
    tag: nightly
    cmd: |
      python - <<'PY'
      import asyncio
      from bridge_buyer_backend import run_daily_snapshot
      # backend picked via SNAPSHOT_BACKEND env (supabase|s3)
      asyncio.run(run_daily_snapshot())
      PY

  # Nightly “flywheel” analytics sweep (forecasts + risk events)
  - name: nightly_forecasts_and_risk
    tag: nightly
    cmd: |
      python - <<'PY'
      import asyncio
      from bridge_buyer_backend import admin_forecast_run
      asyncio.run(admin_forecast_run(horizon_days=30, region=None))
      PY

  # Nightly statements ZIP (per-member) for current UTC date
  - name: nightly_member_statements
    tag: nightly
    cmd: |
      python - <<'PY'
      import asyncio, datetime as dt
      from bridge_buyer_backend import admin_statements_run
      today = dt.datetime.utcnow().date()
      asyncio.run(admin_statements_run(as_of=today))
      PY

  # 4) Your ad-hoc nightly orchestrator (if it chains more stuff)
  - name: nightly_jobs
    tag: nightly
    cmd: python /app/nightly_jobs.py

  # 5) Test sweep (both your custom suite and pytest)
  - name: full_test_suite
    tag: nightly
    cmd: python /app/tests/full_test_suite.py

  - name: pytest_tests_folder
    tag: nightly
    cmd: pytest -q /app/tests --maxfail=5 --disable-warnings

  # If (and only if) you truly have a legacy /app/pytest dir, keep this.
  # Otherwise, delete this block.
  - name: pytest_legacy_folder
    tag: nightly
    cmd: pytest -q /app/pytest --maxfail=5 --disable-warnings

  # ---------- WEEKLY (deeper/slow checks) ----------
  - name: pytest_all
    tag: weekly
    cmd: pytest -q /app --maxfail=10 --disable-warnings

  # Focused “prod safety” & isolation checks weekly, too
  - name: prod_safety_tests
    tag: weekly
    cmd: pytest -q /app/tests/test_prod_safety.py

  - name: tenant_isolation_tests
    tag: weekly
    cmd: pytest -q /app/tests/test_tenant_isolation.py

  # Weekly DR self-check (internal helper; no admin session required)
  - name: weekly_backup_verify
    tag: weekly
    cmd: |
      python - <<'PY'
      import asyncio
      from bridge_buyer_backend import database, _to_utc_z
      async def main():
          row = await database.fetch_one("""
            SELECT ran_at, backend, path, ok, sha256
              FROM backup_proofs
             ORDER BY ran_at DESC
             LIMIT 1
          """)
          # simple non-zero exit if missing/failed
          if not row or not row["ok"]:
              raise SystemExit("No successful backup_proofs row.")
          print("OK latest backup:", _to_utc_z(row["ran_at"]), row["backend"], row["path"])
      asyncio.run(main())
      PY

  # Weekly audit seal for yesterday (no admin route)
  - name: weekly_audit_seal_yesterday
    tag: weekly
    cmd: |
      python - <<'PY'
      import asyncio, datetime as dt, json
      from bridge_buyer_backend import database, _sha256_hex, _canon_json
      async def main():
          d = (dt.datetime.utcnow().date() - dt.timedelta(days=1)).isoformat()
          # recompute tail hash & seal without hitting the admin route
          tail = await database.fetch_one("""
            SELECT seq, event_hash FROM audit_events
            WHERE chain_date=:d ORDER BY seq DESC LIMIT 1
          """, {"d": d})
          final_hash = tail["event_hash"] if tail else _sha256_hex(f"empty:{d}")
          await database.execute("""
            UPDATE audit_events SET sealed=TRUE WHERE chain_date=:d
          """, {"d": d})
          await database.execute("""
            INSERT INTO audit_seals(chain_date, final_hash)
            VALUES (:d, :h)
            ON CONFLICT (chain_date) DO UPDATE SET final_hash=:h, sealed_at=NOW()
          """, {"d": d, "h": final_hash})
          print("Sealed", d, final_hash)
      asyncio.run(main())
      PY
