global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/bridge-rules.yml

scrape_configs:
- job_name: bridge
  metrics_path: /metrics
  static_configs:
  - targets: ['bridge:8000']   # or 'localhost:8000' etc.
