name: DB Backup
on:
  schedule:
    - cron: "0 8 * * *"  # daily at 08:00 UTC
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - run: pg_dump -Fc "$DATABASE_URL" > backup_$(date +%F).dump
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: backup_*.dump
